language: python
python:
  # - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# create a db named test
before_script:
  - psql -c "CREATE DATABASE db_test;" -U postgres
  - psql -c "CREATE USER 'db_admin_name'@'localhost' IDENTIFIED BY 'db_admin_password';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON db_test . * TO 'db_admin_name'@'localhost';" -U postgres

# command to run tests
script:
  - pytest
