language: python
python:
  # - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE db_test;'

# command to run tests
script:
  - pytest
