language: python
python:
  # - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE db_test;'
  - mysql -e 'CREATE USER db_admin_name IDENTIFIED BY db_admin_password;'
  - mysql -e 'GRANT ALL PRIVILEGES ON db_test . * TO db_admin_name;'

# command to run tests
script:
  - pytest
