language: python
python:
  # - "2.7"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

# create a db named test
before_script:
  - psql -c 'create database db_test;' -U postgres

# command to run tests
script:
  - pytest
