language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt

# Setting environment variables
env:
  - ENV_VAR=testing

services:
  - mysql

before_install:
  - mysql -u root -e 'CREATE DATABASE db_test;'
  - mysql -u root -e "CREATE USER 'db_admin_name'@'localhost' IDENTIFIED BY 'db_admin_password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON db_test . * TO 'db_admin_name'@'localhost';"

# command to run tests
script:
  - pytest
